name = "GenieAuthentication"
uuid = "e115e502-7e3a-11e9-29b2-aba8be6c6778"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
