name = "GenieAuthentication"
uuid = "e115e502-7e3a-11e9-29b2-aba8be6c6778"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "0.3.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"

[compat]
Genie = "0"
SearchLight = "0"
julia = "1"
